Appscrunch/Multy-android

app/build.gradle, app/src/main/cpp/scratch.cpp, app/src/main/java/io/multy/Multy.java, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/SeedActivity.java, app/src/main/java/io/multy/ui/fragments/BaseSeedFragment.java, app/src/main/java/io/multy/ui/fragments/dialogs/SeedDialogFragment.java, app/src/main/java/io/multy/ui/fragments/seed/SeedSummaryFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/util/DeviceInfoHelper.java, app/src/main/java/io/multy/util/JniException.java, app/src/main/java/io/multy/util/NativeDataHelper.java, app/src/main/res/drawable/shape_white_rounded.xml, app/src/main/res/layout/dialog_blue.xml, app/src/main/res/layout/fragment_seed.xml, app/src/main/res/layout/fragment_seed_hello.xml, app/src/main/res/layout/fragment_seed_result.xml, app/src/main/res/layout/fragment_seed_summary.xml, app/src/main/res/layout/fragment_seed_validation.xml, app/src/main/res/values/colors.xml
small design improvements, add typeface
=> MUL-208 added base handling for jni exceptions, add blue dialog

app/src/main/java/io/multy/api/ApiServiceInterface.java, app/src/main/java/io/multy/api/MultyApi.java, app/src/main/java/io/multy/api/MultyApiInterface.java, app/src/main/java/io/multy/model/DataManager.java, app/src/main/java/io/multy/model/entities/ExchangePrice.java, app/src/main/java/io/multy/model/requests/AddWalletAddressRequest.java, app/src/main/java/io/multy/storage/DatabaseHelper.java, app/src/main/java/io/multy/ui/activities/AssetActivity.java, app/src/main/java/io/multy/ui/activities/AssetRequestActivity.java, app/src/main/java/io/multy/ui/adapters/WalletAdapter.java, app/src/main/java/io/multy/ui/fragments/AddressesFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/receive/WalletChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/java/io/multy/viewmodels/WalletViewModel.java, app/src/main/res/drawable/shape_bottom_round_main.xml, app/src/main/res/drawable/shape_bottom_round_white.xml, app/src/main/res/layout/fragment_amount_chooser.xml, app/src/main/res/layout/fragment_request_summary.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/integers.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> Mul 381 Fix Receive ui, generate wallet address, fix ui receive

app/build.gradle, app/src/main/java/io/multy/ui/fragments/BaseFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/receive/WalletChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/java/io/multy/viewmodels/AssetSendViewModel.java, app/src/main/java/io/multy/viewmodels/WalletViewModel.java, app/src/main/res/drawable/shape_bottom_round_white.xml, app/src/main/res/layout/fragment_amount_chooser.xml, app/src/main/res/layout/fragment_asset_info.xml, app/src/main/res/layout/fragment_asset_send.xml, app/src/main/res/layout/fragment_send_summary.xml, app/src/main/res/layout/fragment_transaction_fee.xml, app/src/main/res/values/strings.xml
=> MUL_385_fix send ui

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/encryption/MasterKeyGenerator.java, app/src/main/java/io/multy/model/DataManager.java, app/src/main/java/io/multy/storage/DatabaseHelper.java, app/src/main/java/io/multy/ui/activities/AssetActivity.java, app/src/main/java/io/multy/ui/activities/AssetRequestActivity.java, app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/ScanActivity.java, app/src/main/java/io/multy/ui/fragments/BaseFragment.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/main/FastOperationsFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/receive/WalletChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/java/io/multy/viewmodels/AssetSendViewModel.java, app/src/main/res/layout/fragment_request_summary.xml, app/src/main/res/layout/fragment_wallet_chooser.xml, app/src/main/res/values/strings.xml
=> MUL_386_change send/receive flow

app/src/main/java/io/multy/storage/AssetsDao.java, app/src/main/java/io/multy/storage/DatabaseHelper.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/viewmodels/WalletViewModel.java
=> MUL_461_fix_merge_conflicts

app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/SplashActivity.java, app/src/main/res/layout/activity_main.xml
@AndreyGrowl @ihar-paliashchuk please, review
=> added animation to splash activity -> main activity

app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/ui/fragments/BaseFragment.java, app/src/main/java/io/multy/ui/fragments/dialogs/NoConnectionDialogFragment.java, app/src/main/java/io/multy/util/ConnectionReceiver.java, app/src/main/java/io/multy/util/NetworkAvailability.java
=> MUL_507_show_network_dialog

app/src/main/java/io/multy/api/socket/SocketManager.java, app/src/main/java/io/multy/ui/adapters/WalletsAdapter.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/seed/SeedResultFragment.java, app/src/main/java/io/multy/ui/fragments/seed/SeedValidationFragment.java, app/src/main/java/io/multy/util/Constants.java
also fix crash with first init and wrong auth
=> MUL-138 update wallets after sockets event

app/src/main/res/drawable/ic_edit.xml, app/src/main/res/layout/fragment_settings_entrance.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> add entrance settings layout

app/src/main/cpp/scratch.cpp, app/src/main/java/io/multy/api/ApiServiceInterface.java, app/src/main/java/io/multy/api/MultyApi.java, app/src/main/java/io/multy/api/MultyApiInterface.java, app/src/main/java/io/multy/api/socket/SocketManager.java, app/src/main/java/io/multy/model/DataManager.java, app/src/main/java/io/multy/storage/AssetsDao.java, app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/util/NativeDataHelper.java, app/src/main/java/io/multy/util/SendTransactionModel.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java
improve send transaction algorigthm (now HD) but still TODO for new address
=> add support new api for transaction history

app/src/main/java/io/multy/ui/fragments/dialogs/ResetDataDialogFragment.java, app/src/main/java/io/multy/ui/fragments/main/EntranceSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/main/SecuritySettingsFragment.java, app/src/main/res/layout/fragment_settings_entrance.xml, app/src/main/res/layout/fragment_settings_security.xml, app/src/main/res/values/strings.xml
=> add entrance settings fragment

app/src/main/java/io/multy/ui/activities/BaseActivity.java, app/src/main/java/io/multy/ui/fragments/main/EntranceSettingsFragment.java, app/src/main/res/layout/fragment_settings_entrance.xml
=> MUL_645_add showing/hiding password

app/src/main/java/io/multy/ui/fragments/main/SecuritySettingsFragment.java, app/src/main/java/io/multy/ui/fragments/seed/SeedFragment.java, app/src/main/java/io/multy/util/Constants.java
=> MUL_716_add_view_seed_phrase

app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/PinSetupActivity.java, app/src/main/java/io/multy/ui/fragments/dialogs/ResetDataDialogFragment.java, app/src/main/java/io/multy/ui/fragments/main/EntranceSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/main/FastOperationsFragment.java, app/src/main/java/io/multy/ui/fragments/main/SecuritySettingsFragment.java, app/src/main/java/io/multy/ui/fragments/main/SettingsFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/fragment_settings_entrance.xml, app/src/main/res/layout/fragment_settings_security.xml, app/src/main/res/values/strings.xml
=> MUL_721_settings

app/src/main/java/io/multy/ui/fragments/main/EntranceSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/main/SettingsFragment.java, app/src/main/res/color/selector_switch_track.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/fragment_settings_entrance.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> MUL_723_add_switch_style

app/src/main/java/io/multy/model/entities/TransactionHistory.java, app/src/main/java/io/multy/model/responses/WalletsResponse.java, app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java, app/src/main/java/io/multy/viewmodels/AssetSendViewModel.java, app/src/main/res/layout/fragment_amount_chooser.xml
fix for create wallet with wrong index
fix crash when pressing back on send summary
fix dual currency typing on amount screen
fix wrong sorting for tx history
code refactor
=> MUL-344 bugfix and refactor

app/src/main/java/io/multy/ui/adapters/WalletAdapter.java, app/src/main/java/io/multy/ui/adapters/WalletsAdapter.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/receive/WalletChooserFragment.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java
=> MUL_726_fix_getting_exchange_price_on_receive_screens

app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java, app/src/main/res/values/strings.xml
@AndreyGrowl @ihar-paliashchuk 
please review
=> transaction info screen fix for count of confirmations

app/src/main/java/io/multy/ui/activities/SplashActivity.java, app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java
=> fixed donation on transaction info screen

app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java
@AndreyGrowl  @ihar-paliashchuk please review
=> fixed double print btc into transaction info screen

app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/ui/activities/AmountChooserActivity.java, app/src/main/java/io/multy/ui/activities/PinSetupActivity.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/util/DeepLinkShareHelper.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/res/layout/activity_asset_request.xml, app/src/main/res/layout/fragment_amount_chooser.xml, app/src/main/res/layout/layout_pin.xml
=> MUL_736_fix_bugs_on_receive

app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java
@AndreyGrowl @ihar-paliashchuk please review
=> protection when currency rates is null

app/src/main/java/io/multy/Multy.java
@AndreyGrowl @ihar-paliashchuk please review
=> fixed loop initialization if something went wrong

app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/SplashActivity.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/java/io/multy/util/DeepLinkShareHelper.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/res/values/strings.xml
=> MUL_782_fill_in_branch_universal_object

app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/fcm/MultyFirebaseMessagingService.java, app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/activities/SplashActivity.java, app/src/main/java/io/multy/ui/fragments/BaseSeedFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/seed/SeedResultFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java, app/src/main/java/io/multy/util/analytics/Analytics.java, app/src/main/java/io/multy/util/analytics/AnalyticsConstants.java, app/src/main/java/io/multy/viewmodels/AssetsViewModel.java, app/src/main/res/values/strings.xml
=> MUL_514_add_new_analytics_events

app/build.gradle, app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java, app/src/main/res/layout/fragment_send_summary.xml, app/src/main/res/values/strings.xml
=> MUL_896_fix_deep_link_flow

app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/fragments/dialogs/ResetDataDialogFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java
=> MUL_767_fix_reset_all_data

app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/res/drawable/ic_slide_to_send.xml, app/src/main/res/drawable/ic_slide_to_send_finish.xml, app/src/main/res/layout/fragment_send_summary.xml, app/src/main/res/values/strings.xml
@AndreyGrowl @ihar-paliashchuk please review
=> Mul 879 slide to send result new

app/src/main/AndroidManifest.xml, app/src/main/java/io/multy/ui/activities/AmountChooserActivity.java, app/src/main/java/io/multy/ui/activities/BaseActivity.java, app/src/main/java/io/multy/ui/activities/MainActivity.java, app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_seed_validation.xml, app/src/main/res/layout/fragment_transaction_fee.xml, app/src/main/res/layout/holder_pin.xml
…ansaction fee screen @AndreyGrowl @ihar-paliashchuk please review
=> Mul 781 show hide keyboard flow

app/src/main/java/io/multy/ui/fragments/BaseFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/dialogs/NoConnectionDialogFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java
=> Mul_923_fix_no_connection_dialog

app/src/main/cpp/scratch.cpp, app/src/main/java/io/multy/ui/activities/AssetActivity.java, app/src/main/java/io/multy/ui/adapters/AssetSettingAddressesAdapter.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/asset/SettingAssetAddressesFragment.java, app/src/main/java/io/multy/ui/fragments/dialogs/PrivateKeyDialogFragment.java, app/src/main/java/io/multy/util/NativeDataHelper.java, app/src/main/java/io/multy/viewmodels/WalletViewModel.java, app/src/main/res/drawable/ic_copy_to_clipboard.xml, app/src/main/res/layout/bottom_sheet_private_key.xml, app/src/main/res/layout/fragment_asset_setting_addresses.xml, app/src/main/res/layout/item_asset_setting_address.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
@AndreyGrowl  @ihar-paliashchuk please review
=> Mul 794 show my private key

app/src/main/java/io/multy/viewmodels/WalletViewModel.java, app/src/main/res/drawable/ic_share.xml, app/src/main/res/layout/bottom_sheet_private_key.xml, app/src/main/res/layout/item_asset_setting_address.xml
=> bugfix and smal ui improvements of private key screen

app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java, app/src/main/java/io/multy/ui/fragments/asset/CurrencyChooserFragment.java, app/src/main/java/io/multy/ui/fragments/main/SettingsFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java, app/src/main/res/layout/fragment_asset_send.xml, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_request_summary.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> code refactored, missing fragments added

app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java
(cherry picked from commit a41bce0)
please review
=> fixed fiat amount

app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java
(cherry picked from commit b6e16da)
=> improved speed of creating qr code and improved ui for qr creating

app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java
@AndreyGrowl please review
fix for rejected and blocked transactions
=> fixed incoming transaction fiat amount

app/src/main/java/io/multy/model/entities/AuthEntity.java, app/src/main/java/io/multy/storage/SettingsDao.java, app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java, app/src/main/java/io/multy/ui/fragments/dialogs/WalletChooserDialogFragment.java, app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/java/io/multy/viewmodels/WalletViewModel.java
add app version
fix scaning QR code with amount
fix displaying transaction addresses
=> MUL-1349 pre release bugfix

app/build.gradle, app/src/main/java/io/multy/storage/SettingsDao.java, app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java
this version uploaded to market
=> beta release

app/src/main/java/io/multy/api/socket/SocketManager.java, app/src/main/java/io/multy/model/entities/wallet/Wallet.java, app/src/main/java/io/multy/storage/SettingsDao.java, app/src/main/java/io/multy/ui/adapters/EthTransactionsAdapter.java, app/src/main/java/io/multy/ui/fragments/asset/AssetSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java, app/src/main/java/io/multy/ui/fragments/asset/EthTransactionInfoFragment.java, app/src/main/java/io/multy/util/Constants.java, app/src/main/res/layout/bottom_sheet_wallet_action.xml, app/src/main/res/layout/fragment_eth_transaction_info.xml, app/src/main/res/values/strings.xml
wrong check for testnet donation address, transactions adapter for eth to usd exchange and sorting of transactions, blocked show private key for ethereum, added ethereum transaction info screen,
=> MUL-1354 ETH Transaction info screen.

app/build.gradle, app/constants.gradle, app/scripts.gradle, build.gradle
=> Mul 1338 split the build.gradle file into blocks of scripts and variables

app/src/main/java/io/multy/model/entities/wallet/Wallet.java, app/src/main/java/io/multy/storage/SettingsDao.java, app/src/main/java/io/multy/ui/activities/AmountChooserActivity.java, app/src/main/java/io/multy/ui/activities/AssetRequestActivity.java, app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/adapters/AssetSettingAddressesAdapter.java, app/src/main/java/io/multy/ui/fragments/asset/AssetSettingsFragment.java, app/src/main/java/io/multy/ui/fragments/asset/SettingAssetAddressesFragment.java, app/src/main/java/io/multy/ui/fragments/dialogs/PrivateKeyDialogFragment.java, app/src/main/java/io/multy/ui/fragments/receive/AmountChooserFragment.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/ui/fragments/send/ethereum/EthAmountChooserFragment.java, app/src/main/java/io/multy/util/CryptoFormatUtils.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java
=> MUL-1444 make "show my private key" for eth

.gitignore, app/src/main/java/io/multy/api/MultyApi.java, app/src/main/java/io/multy/storage/AssetsDao.java
=> auth and pending fix

app/src/main/java/io/multy/api/socket/SocketManager.java, app/src/main/java/io/multy/model/entities/wallet/Wallet.java, app/src/main/java/io/multy/storage/SettingsDao.java, app/src/main/java/io/multy/ui/adapters/MyWalletsAdapter.java, app/src/main/java/io/multy/ui/fragments/DonationFragment.java, app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java, app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java, app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java, app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java, app/src/main/res/layout/fragment_donation.xml
=> MUL-1517-keyboard-optimization

app/src/main/java/io/multy/ui/activities/AssetSendActivity.java, app/src/main/java/io/multy/ui/adapters/ChainAdapter.java, app/src/main/java/io/multy/ui/adapters/EthTransactionsAdapter.java, app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java, app/src/main/java/io/multy/ui/fragments/asset/EthAssetInfoFragment.java, app/src/main/java/io/multy/util/NumberFormatter.java, app/src/main/res/layout/fragment_asset_send.xml, app/src/main/res/layout/fragment_eth_asset_info.xml, app/src/main/res/layout/view_assets_action_add.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
fixed decimal with comma via qr, renamed description of chains on create asset screen, fixed empty views notifications on eth asset screen, replaced comma with dot for eth, changed wireless scan icon
=> MUL-1590-Bugfix

app/src/main/java/io/multy/model/entities/wallet/EthWallet.java, app/src/main/java/io/multy/ui/fragments/asset/EthAssetInfoFragment.java
fix displaying eth pending balances
=> MUL-1590 eth balance fix

app/src/main/java/io/multy/api/socket/BlueSocketManager.java, app/src/main/java/io/multy/ui/activities/ScanActivity.java, app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java, app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java, app/src/main/res/layout/fragment_request_summary.xml
fix qr code scan and generating
add wake lock for request screen
removed old socket event btc transaction update
=> MUL-1609-release-fix

app/src/main/java/io/multy/ui/activities/ScanActivity.java
=> fixed qr scanner
